pipeline{
    agent none 
    
    stages{
        stage("backend build"){
            agent{
                docker{
                    image "maven:3.8.1-adoptopenjdk-11"
                    arg "-u root"
                }
            }
            steps{
                echo "building java backend"
                sh "mvn clean install"
            }
        }
        stage("frontend build"){
            agent{
                docker{
                    image "node:16-alpine"
                    arg "-u root"
                }
            }
            steps{
                echo "building node frontend"
                sh "npm install"
                sh "npm run build"
                
            }
        }
    }
    post{
        success{
            echo "build completed sucessfully"
        }
        failure{
            echo "build failed check the logs above"
        }
    }
}
